package com.example.app.controller;

import com.example.app.api.DefaultApi;
import com.example.app.model.FeatureDTO;
import java.util.List;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RestController;

/** Simple implementation of the interface generated by OpenAPI for demonstration. */
@RestController
public class FeatureController implements DefaultApi {

  @Override
  public ResponseEntity<List<FeatureDTO>> featureGet() {
    FeatureDTO sample = new FeatureDTO().id(1L).name("Sample feature");
    return ResponseEntity.ok(List.of(sample));
  }

  @Override
  public ResponseEntity<String> statusGet() {
    return ResponseEntity.ok("alive");
  }
}
