package com.example.app.controller;

import com.example.app.api.DefaultApi;
import com.example.app.model.FeatureDTO;
import com.example.app.model.UserDTO;
import com.example.app.model.UserRole;
import com.example.app.user.UserEntity;
import com.example.app.user.UserService;
import java.util.List;
import java.util.stream.Collectors;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import jakarta.validation.Valid;
import org.springframework.web.bind.annotation.RestController;

/** Simple implementation of the interface generated by OpenAPI for demonstration. */
@RestController
public class FeatureController implements DefaultApi {

  private final UserService userService;

  public FeatureController(UserService userService) {
    this.userService = userService;
  }

  @Override
  public ResponseEntity<List<FeatureDTO>> featureGet() {
    FeatureDTO sample = new FeatureDTO().id(1L).name("Sample feature");
    return ResponseEntity.ok(List.of(sample));
  }

  @Override
  public ResponseEntity<String> statusGet() {
    return ResponseEntity.ok("alive");
  }

  @Override
  public ResponseEntity<List<UserDTO>> usersGet() {
    List<UserDTO> users = userService.findAll().stream()
        .map(u -> new UserDTO()
            .id(u.getId())
            .role(UserRole.valueOf(u.getRole().name()))
            .email(u.getEmail()))
        .collect(Collectors.toList());
    return ResponseEntity.ok(users);
  }

  @Override
  public ResponseEntity<Void> usersPost(@Valid UserDTO userDTO) {
    UserEntity entity = new UserEntity(
        null,
        com.example.app.user.UserRole.valueOf(userDTO.getRole().name()),
        userDTO.getEmail(),
        userDTO.getPasswordHash());
    userService.create(entity);
    return ResponseEntity.status(HttpStatus.CREATED).build();
  }
}
