include:
  - "services/backend/**"
  - "apps/guest_app/**"
  - "apps/admin_app/**"
  - "apps/cleaner_app/**"
  - "services/backend/src/main/java/**"
  - "services/backend/src/main/java/com/example/app/user/UserEntity.java"
  - "config.yml"
exclude:
  - "services/backend/target/generated-sources/**"
  - "apps/**/lib/**/*.g.dart"
backup_dir: ".backups"
backup_retention_days: 7
generated_openapi: "services/backend/src/main/resources/openapi.yaml"
