# docker-compose.yml


services:
  backend:
    build:
      context: ./services/backend
    container_name: template-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - app-net

  # مثال لخدمة DB مستقبلية
  # postgres:
  #   image: postgres:16
  #   environment:
  #     POSTGRES_USER: template
  #     POSTGRES_PASSWORD: template
  #     POSTGRES_DB: template
  #   ports:
  #     - "5432:5432"
  #   networks:
  #     - app-net

networks:
  app-net:
    driver: bridge
