services:
  backend:
    build:
      context: ./services/backend
    container_name: template-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
